<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.aisys</groupId>
        <artifactId>aisys-platform</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>aisys-common</artifactId>
    <packaging>pom</packaging>
    <name>aisys-common (公共模块聚合)</name>

    <modules>
        <module>aisys-common-core</module>
        <module>aisys-common-security</module>
        <module>aisys-common-mybatis</module>
        <module>aisys-common-redis</module>
        <module>aisys-common-s3</module>
        <module>aisys-common-mq</module>
        <module>aisys-common-log</module>
        <module>aisys-common-feign</module>
    </modules>
</project>
